version: "3.9"
services:
    mongo:
        image: "imagen-mongo"
        build: .
        volumes:
            - type: bind
              source: .
              target: "/source"

        tty: true

