version: "3.9"
services:
    mongo:
        image: "imagen-mongo"
        build: .
        volumes:
            - type: bind
              source: "./data"
              target: "/data"
        ports:
          - 27017:27017


        tty: true

