version: "3.9"
services:
    cassandra:
        image: "imagen-cassandra"
        build: .
        volumes:
            - type: bind
              source: .
              target: "/source"

        tty: true

